[settings]
idiomatic_version_file = false
experimental = true

[settings.python]
uv_venv_auto = true

[tools]
node = "22"
ruby = "3.3"
python = "3.13"
uv = "latest"
lua = ["5.1"]
go = "1.24.1"
opam = "2.3.0"
