return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "javascript",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "json",
      "lua",
      "make",
      "matlab",
      "markdown",
      "markdown_inline",
      "ninja",
      "ruby",
      "rust",
      "python",
      "regex",
      "rst",
      "vim",
      "yaml",
    },
  },
}
