return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "css",
      "embedded_template",
      "html",
      "javascript",
      "json",
      "lua",
      "make",
      "matlab",
      "markdown",
      "markdown_inline",
      "ninja",
      "ruby",
      "python",
      "regex",
      "rst",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
