line-length = 88
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
  "D",   # pydocstyle
  "C90", # complexity
  "I",   # isort
  "B",   # flake8-bugbear
]

[pydocstyle]
convention = "google"
